#!/usr/bin/env python3
"""
Automation #01 — Daily AI & Data Analytics learning briefing.

Scheduled by a launch agent (schedule/com.omrisabag.daily-ai-briefing.plist)
at 08:00 daily. Can also be run by hand:

    python run.py                       # generate today's entry, write the log
    python run.py --dry-run             # write output/_preview.md only; real log untouched
    python run.py --date 2026-09-08     # pretend it is that day (for testing)
    python run.py --print-prompt        # also show the exact prompt sent to Claude

Each run:
  1. Works out today's date and yesterday's calendar day (local time).
  2. Collects yesterday's activity across ~/Documents/Python_Projects:
       - git commits from every repo directly under it
       - files created / modified that day (mtime), minus obvious noise
  3. Asks Claude (via the `claude` CLI, with web search) for today's entry:
       one AI development, one analyst topic, one learning prompt, and a
       judged recap of yesterday's activity.
  4. Prepends that entry to output/daily_ai_analytics_briefing.md (newest
     first), replacing any existing entry for the same date so re-runs are safe.

Nothing is installed. Uses the existing `claude` CLI and its current auth.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import random
import re
import subprocess
import time
import traceback
from pathlib import Path

# ------------------------------------------------------------------- schedule
# SINGLE SOURCE OF TRUTH for when this runs. Keep it in sync with both READMEs.
# Scheduled by a macOS launch agent:
#     schedule/com.omrisabag.daily-ai-briefing.plist  ->  ~/Library/LaunchAgents/
#     fires `python run.py` at 08:00 system-local time (Asia/Jerusalem) daily.
# `python run.py` by hand still works, for manual and --dry-run testing.
# To change the time or cadence, ask Claude to update this block, the .plist,
# and both READMEs together.
RUN_MODE = "scheduled"            # "manual" | "scheduled" (launchd agent installed)
RUN_TIME_LOCAL = "08:00"          # HH:MM, 24h
RUN_TIMEZONE = "Asia/Jerusalem"   # Israel local time (follows the Mac's timezone)

# --------------------------------------------------------------------- config
HERE = Path(__file__).resolve().parent
PROJECTS_ROOT = HERE.parent.parent  # ~/Documents/Python_Projects
OUTPUT_FILE = HERE / "output" / "daily_ai_analytics_briefing.md"
PREVIEW_FILE = HERE / "output" / "_preview.md"  # --dry-run target; gitignored
LOG_FILE = HERE / "logs" / "run.log"

CLAUDE_BIN = "claude"
CLAUDE_MODEL = "sonnet"
CLAUDE_TIMEOUT_S = 600

# When scanning Python_Projects for "what changed yesterday", ignore these.
SKIP_DIRS = {
    ".git", "__pycache__", ".ipynb_checkpoints", "node_modules",
    ".pytest_cache", ".mypy_cache", ".venv", "_cache", ".idea",
}
SKIP_SUFFIXES = {".pyc", ".pyo"}
SKIP_NAMES = {".DS_Store"}
SKIP_PATHS = {OUTPUT_FILE.resolve(), PREVIEW_FILE.resolve(), LOG_FILE.resolve()}
MAX_CHANGED_FILES = 200

INTRO = """\
# Daily AI & Data Analytics Learning Briefing

A running log, newest entry first, generated by
`Automations/01_daily_ai_briefing/run.py`. Each morning's entry has four parts:

1. **AI development** — one recent, genuinely interesting thing from the AI
   world, with a source.
2. **Analyst topic** — one data-analytics concept, technique, or tool worth
   knowing.
3. **Learning prompt** — a small exercise to try that day.
4. **Yesterday's ground covered** — a short, judged recap of what changed in
   `Python_Projects/` the day before (new work and lessons — not every routine
   edit).

---
"""

PROMPT_TEMPLATE = """\
You are writing today's entry for a personal daily learning log kept by a data \
analyst who is deepening their AI and data-analytics knowledge. Today is {today} \
(a {weekday}). "Yesterday" means {yesterday}.

Produce ONE Markdown entry and nothing else - no preamble, no code fences. \
Start on the very first line with this exact heading:

## {today}

Then exactly these four sections, in this order, with these headings:

### 1. AI development
One recent (ideally within the last ~7 days) and genuinely interesting \
development in AI - a release, a result, a policy move, an idea. 2-4 sentences, \
concrete, no hype. Finish with a Markdown link to a source. Use web search to \
find and verify it.

### 2. Analyst topic worth knowing
One data-analytics concept, technique, statistical idea, or tool worth a \
practitioner's time. 2-4 sentences. A source link is welcome but optional.

### 3. Learning prompt
One small, concrete exercise the analyst can do today in 15-30 minutes - tied \
to section 2 where that makes sense. 1-2 sentences.

### 4. Yesterday's ground covered
A short bulleted recap of what was actually worked on in the Python_Projects \
workspace on {yesterday}, based only on the ACTIVITY DATA below. Apply \
judgement: starting or finishing a project, a new analysis, a new technique, a \
shipped deliverable - each worth a bullet. Routine re-saves, tiny edits, and \
system/cache files - skip them. 2-5 bullets. If the data shows nothing \
meaningful, write exactly this line and nothing else in the section:
_Nothing notable recorded for {yesterday}._

End the entry with a line containing only three dashes:

---

--- ACTIVITY DATA for {yesterday} ---

Git commits:
{commits}

Files created or modified (path relative to Python_Projects/):
{changed}
"""


# ------------------------------------------------------------------- helpers
# Set False by --dry-run so test runs never touch logs/run.log or state/.
_LOG_TO_FILE = True


def log(msg: str) -> None:
    print(msg)
    if not _LOG_TO_FILE:
        return
    LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
    stamp = dt.datetime.now().isoformat(timespec="seconds")
    with LOG_FILE.open("a") as fh:
        fh.write(f"{stamp}  {msg}\n")


# ------------------------------------------------------------ failure handling
# Identical block across automations 01 / 02 / 03 (02 & 03 add _TransientHTTP).
STATE_FILE = HERE / "state" / "last_run.json"
_RUN: dict = {"status": "error", "detail": "run did not complete", "entry": None}


class ClaudeError(RuntimeError):
    """A retryable `claude` CLI failure (non-zero exit / timeout)."""


def _record(status: str, detail: str, entry: str | None = None) -> None:
    _RUN.update(status=status, detail=detail)
    if entry is not None:
        _RUN["entry"] = entry


def _retry(fn, *, attempts: int, base_delay: float, transient: tuple):
    for i in range(attempts):
        try:
            return fn()
        except transient as exc:
            if i == attempts - 1:
                raise
            wait = base_delay * (2 ** i) + random.uniform(0, base_delay)
            log(f"transient failure ({exc}); retry {i + 1}/{attempts - 1} "
                f"in {wait:.1f}s")
            time.sleep(wait)


def write_state(exit_code: int, started_at: str) -> None:
    prev: dict = {}
    try:
        prev = json.loads(STATE_FILE.read_text())
    except Exception:  # noqa: BLE001 - missing / unreadable is fine
        pass
    cf = int(prev.get("consecutive_failures", 0))
    cf = cf + 1 if _RUN["status"] == "error" else 0
    STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    STATE_FILE.write_text(json.dumps({
        "automation": HERE.name,
        "started_at": started_at,
        "finished_at": dt.datetime.now().isoformat(timespec="seconds"),
        "status": _RUN["status"],
        "exit_code": exit_code,
        "entry": _RUN["entry"],
        "detail": _RUN["detail"],
        "consecutive_failures": cf,
    }, indent=2) + "\n")


def yesterday_window(today: dt.date) -> tuple[dt.datetime, dt.datetime]:
    start = dt.datetime.combine(today - dt.timedelta(days=1), dt.time.min)
    end = dt.datetime.combine(today, dt.time.min)
    return start, end


def find_repos() -> list[Path]:
    return sorted(
        d for d in PROJECTS_ROOT.iterdir()
        if d.is_dir() and (d / ".git").is_dir()
    )


def collect_git_commits(start: dt.datetime, end: dt.datetime) -> str:
    blocks: list[str] = []
    for repo in find_repos():
        try:
            proc = subprocess.run(
                [
                    "git", "-C", str(repo), "log", "--all",
                    f"--since={start.isoformat()}",
                    f"--until={end.isoformat()}",
                    "--pretty=format:- %h %s", "--shortstat", "--no-color",
                ],
                capture_output=True, text=True, timeout=30,
            )
        except Exception as exc:  # noqa: BLE001 - report and move on
            blocks.append(f"[{repo.name}] git log failed: {exc}")
            continue
        body = proc.stdout.strip()
        if body:
            blocks.append(f"repo: {repo.name}\n{body}")
    return "\n\n".join(blocks) if blocks else "(no commits yesterday)"


def _walk(root: Path):
    stack = [root]
    while stack:
        current = stack.pop()
        try:
            entries = list(current.iterdir())
        except OSError:
            continue
        for entry in entries:
            if entry.is_symlink():
                continue
            if entry.is_dir():
                if entry.name not in SKIP_DIRS:
                    stack.append(entry)
            elif entry.name not in SKIP_NAMES and entry.suffix not in SKIP_SUFFIXES:
                if entry.resolve() not in SKIP_PATHS:
                    yield entry


def collect_changed_files(start: dt.datetime, end: dt.datetime) -> str:
    start_ts, end_ts = start.timestamp(), end.timestamp()
    hits: list[str] = []
    for path in _walk(PROJECTS_ROOT):
        try:
            mtime = path.stat().st_mtime
        except OSError:
            continue
        if start_ts <= mtime < end_ts:
            hits.append(path.relative_to(PROJECTS_ROOT).as_posix())
    if not hits:
        return "(no files modified yesterday)"
    hits.sort()
    shown = hits[:MAX_CHANGED_FILES]
    text = "\n".join(shown)
    if len(hits) > MAX_CHANGED_FILES:
        text += f"\n... (+{len(hits) - MAX_CHANGED_FILES} more)"
    return text


def generate_entry(
    today: str, yesterday: str, weekday: str, commits: str, changed: str,
    print_prompt: bool = False,
) -> str:
    prompt = PROMPT_TEMPLATE.format(
        today=today, yesterday=yesterday, weekday=weekday,
        commits=commits, changed=changed,
    )
    if print_prompt:
        print("\n----- PROMPT SENT TO CLAUDE -----")
        print(prompt)
        print("----- END PROMPT -----\n")

    def _call() -> str:
        proc = subprocess.run(
            [
                CLAUDE_BIN, "-p", prompt,
                "--output-format", "text",
                "--permission-mode", "dontAsk",
                "--allowedTools", "WebSearch", "WebFetch",
                "--model", CLAUDE_MODEL,
            ],
            capture_output=True, text=True, timeout=CLAUDE_TIMEOUT_S, cwd=str(HERE),
        )
        if proc.returncode != 0:
            raise ClaudeError(
                f"claude CLI exited {proc.returncode}\n{proc.stderr.strip()}"
            )
        return proc.stdout

    raw = _retry(_call, attempts=2, base_delay=5,
                 transient=(ClaudeError, subprocess.TimeoutExpired))

    entry = raw.strip()
    if entry.startswith("```"):
        entry = entry.split("\n", 1)[1] if "\n" in entry else ""
        entry = entry.rstrip()
        if entry.endswith("```"):
            entry = entry[:-3].rstrip()
    if not entry.startswith(f"## {today}"):
        raise RuntimeError(f"unexpected entry start:\n{entry[:300]}")
    return entry


def _drop_existing_entry(entries_block: str, today: str) -> str:
    out: list[str] = []
    skipping = False
    for line in entries_block.splitlines():
        if re.match(r"^## \d{4}-\d{2}-\d{2}\b", line):
            skipping = line.startswith(f"## {today}")
        if not skipping:
            out.append(line)
    return "\n".join(out).strip("\n")


def upsert_entry(entry: str, today: str) -> str:
    content = OUTPUT_FILE.read_text() if OUTPUT_FILE.exists() else INTRO

    marker = "\n---\n"
    idx = content.find(marker)
    if idx == -1:
        head = INTRO
        rest = ""
    else:
        head = content[: idx + len(marker)]
        rest = content[idx + len(marker):].lstrip("\n")

    rest = _drop_existing_entry(rest, today)

    parts = [head.rstrip(), "", entry.rstrip()]
    if rest:
        parts += ["", rest.rstrip()]
    return "\n".join(parts).rstrip() + "\n"


# ---------------------------------------------------------------------- main
def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate the daily AI & data-analytics learning briefing.",
    )
    parser.add_argument(
        "--date", metavar="YYYY-MM-DD",
        help="treat this as 'today' instead of the real date (for testing)",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="print the entry that would be written; touch no files",
    )
    parser.add_argument(
        "--print-prompt", action="store_true",
        help="also print the exact prompt sent to the claude CLI",
    )
    args = parser.parse_args(argv)
    if args.date:
        try:
            args.today = dt.date.fromisoformat(args.date)
        except ValueError:
            parser.error(f"--date must be YYYY-MM-DD, got {args.date!r}")
    else:
        args.today = dt.date.today()
    return args


def main(argv: list[str] | None = None) -> int:
    global _LOG_TO_FILE
    args = parse_args(argv)
    today = args.today
    if args.dry_run:
        _LOG_TO_FILE = False

    yesterday = today - dt.timedelta(days=1)
    start, end = yesterday_window(today)
    today_s, yesterday_s = today.isoformat(), yesterday.isoformat()

    mode = "DRY RUN" if args.dry_run else "run"
    log(f"{mode} start - today={today_s} yesterday={yesterday_s}")

    commits = collect_git_commits(start, end)
    changed = collect_changed_files(start, end)
    n_changed = 0 if changed.startswith("(no files") else len(changed.splitlines())
    log(f"activity gathered - git block {len(commits)} chars, {n_changed} changed paths")

    try:
        entry = generate_entry(
            today_s, yesterday_s, today.strftime("%A"), commits, changed,
            print_prompt=args.print_prompt,
        )
    except Exception as exc:  # noqa: BLE001 - keep the existing file intact
        log(f"ERROR: {exc}")
        _record("error", str(exc), entry=today_s)
        return 1

    new_body = upsert_entry(entry, today_s)

    if args.dry_run:
        PREVIEW_FILE.parent.mkdir(parents=True, exist_ok=True)
        PREVIEW_FILE.write_text(new_body)
        log(f"dry run - {OUTPUT_FILE.name} NOT touched; full preview at "
            f"{PREVIEW_FILE.relative_to(PROJECTS_ROOT)} ({len(new_body)} bytes) "
            f"- open it in Markdown preview")
        return 0

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(new_body)
    detail = f"wrote {OUTPUT_FILE.relative_to(PROJECTS_ROOT)} ({len(new_body)} bytes)"
    log(detail)
    _record("ok", detail, entry=today_s)
    return 0


if __name__ == "__main__":
    _started = dt.datetime.now().isoformat(timespec="seconds")
    _code, _ran = 1, False
    try:
        _code = main()
        _ran = True
    except Exception as exc:  # noqa: BLE001 - record, then re-raise the exit
        _record("error", f"uncaught: {exc!r}")
        traceback.print_exc()
        _ran = True
    finally:
        # skip on --help / bad args (SystemExit from argparse, _ran stays False)
        # and on --dry-run (_LOG_TO_FILE is False)
        if _ran and _LOG_TO_FILE:
            write_state(_code, _started)
    raise SystemExit(_code)
