#!/usr/bin/env python3
"""
Automation #05 — Weekly Music Release Tracker.

Scheduled by a launch agent (schedule/com.omrisabag.weekly-music-releases.plist)
every Sunday at 12:00 (Asia/Jerusalem). Can also be run by hand:

    python run.py                       # generate this week's entry, write the log
    python run.py --dry-run             # write output/_preview.md only; real log untouched
    python run.py --date 2026-09-27     # pretend today is that date (testing / backfill)

Each run:
  1. Reads the followed-artist watch list fresh from a local spreadsheet
     (Music tab col C + Listen tab col A, deduped) — no hardcoded artist list.
  2. Resolves each artist name to a MusicBrainz ID, cached locally so only
     genuinely new names hit the search API on later runs.
  3. Checks MusicBrainz for studio albums (excludes Live/Compilation/EP/
     Soundtrack/etc.) with a release date inside this week's window
     (Sun 00:00 -> following Sun 00:00, Asia/Jerusalem).
  4. For each hit, works out its position in that artist's studio
     discography (blank if the full discography can't be confirmed).
  5. Prepends the week's table (or a "no releases" message) to
     output/weekly_music_releases.md (newest first), replacing any existing
     entry for the same week so re-runs are safe.

Deliberately different from 01-03: entirely deterministic, no `claude` call.
The output is a plain data table with no prose/judgment required, so there's
nothing for a model to usefully add. Stdlib + pandas/openpyxl (already
installed via Anaconda) — nothing new is installed.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import random
import re
import time
import traceback
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

import pandas as pd

# ------------------------------------------------------------------- schedule
# SINGLE SOURCE OF TRUTH for when this runs. Keep in sync with the .plist and
# this folder's README (change it by asking Claude, not by hand-editing one
# place). Purely documentation here — the window math derives entirely from
# the calendar date (see week_window()), not from these constants; launchd
# alone controls the actual firing time.
RUN_MODE = "scheduled"           # "manual" | "scheduled" (launchd agent installed)
RUN_DOW = "Sun"                  # weekly, Sunday
RUN_TIME_LOCAL = "12:00"         # HH:MM, 24h
RUN_TIMEZONE = "Asia/Jerusalem"  # follows the Mac's timezone

# --------------------------------------------------------------------- config
HERE = Path(__file__).resolve().parent
PROJECTS_ROOT = HERE.parent.parent
OUTPUT_FILE = HERE / "output" / "weekly_music_releases.md"
PREVIEW_FILE = HERE / "output" / "_preview.md"
LOG_FILE = HERE / "logs" / "run.log"

WATCHLIST_XLSX = Path("/Users/omrisabag/Documents/שונות/Bills 2026.xlsx")
WATCHLIST_MUSIC_SHEET, WATCHLIST_MUSIC_COL = "Music", "C"     # artist names, one per cell
WATCHLIST_LISTEN_SHEET, WATCHLIST_LISTEN_COL = "Listen", "A"  # "artist - album" cells

MB_BASE = "https://musicbrainz.org/ws/2"
MB_USER_AGENT = "OmriAutomations-WeeklyMusicReleases/1.0"
MB_SEARCH_SCORE_THRESHOLD = 90    # artist-search confidence floor; below -> unmatched
MB_RATE_DELAY_S = 1.05            # MusicBrainz asks for ~1 request/sec, unauthenticated
MB_MAX_RELEASE_GROUPS = 100       # the API's own page-size ceiling

HTTP_TIMEOUT_S = 30

INTRO = """\
# Weekly Music Release Tracker

A running log, newest entry first, generated by
`Automations/05_weekly_music_releases/run.py`. Each week's entry covers
Sunday 00:00 to the following Sunday 00:00 (Asia/Jerusalem) and lists every
new **studio album** (no live albums, compilations, EPs, or soundtracks)
released in that window by an artist on the watch list — read fresh each run
from `Music` (col C) and `Listen` (col A) in the source spreadsheet.
Entirely deterministic: every row is looked up directly from MusicBrainz,
nothing here is model-generated.

---
"""


# ------------------------------------------------------------------- helpers
# Set False by --dry-run so test runs never touch logs/run.log or state/.
_LOG_TO_FILE = True


def log(msg: str) -> None:
    print(msg)
    if not _LOG_TO_FILE:
        return
    LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
    stamp = dt.datetime.now().isoformat(timespec="seconds")
    with LOG_FILE.open("a") as fh:
        fh.write(f"{stamp}  {msg}\n")


# ------------------------------------------------------------ failure handling
# Same shape as the other automations' shared block (no ClaudeError here —
# this automation never calls `claude`).
STATE_FILE = HERE / "state" / "last_run.json"
ARTIST_CACHE_FILE = HERE / "state" / "artist_cache.json"
_RUN: dict = {"status": "error", "detail": "run did not complete", "entry": None}


class GatherError(RuntimeError):
    """A data-gathering failure that aborts without touching real files."""


class _TransientHTTP(GatherError):
    """A retryable HTTP failure (5xx / connection). Still a GatherError."""


def _record(status: str, detail: str, entry: str | None = None) -> None:
    _RUN.update(status=status, detail=detail)
    if entry is not None:
        _RUN["entry"] = entry


def _retry(fn, *, attempts: int, base_delay: float, transient: tuple):
    for i in range(attempts):
        try:
            return fn()
        except transient as exc:
            if i == attempts - 1:
                raise
            wait = base_delay * (2 ** i) + random.uniform(0, base_delay)
            log(f"transient failure ({exc}); retry {i + 1}/{attempts - 1} "
                f"in {wait:.1f}s")
            time.sleep(wait)


def write_state(exit_code: int, started_at: str) -> None:
    prev: dict = {}
    try:
        prev = json.loads(STATE_FILE.read_text())
    except Exception:  # noqa: BLE001 - missing / unreadable is fine
        pass
    cf = int(prev.get("consecutive_failures", 0))
    cf = cf + 1 if _RUN["status"] == "error" else 0
    STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
    STATE_FILE.write_text(json.dumps({
        "automation": HERE.name,
        "started_at": started_at,
        "finished_at": dt.datetime.now().isoformat(timespec="seconds"),
        "status": _RUN["status"],
        "exit_code": exit_code,
        "entry": _RUN["entry"],
        "detail": _RUN["detail"],
        "consecutive_failures": cf,
    }, indent=2) + "\n")


def http_get_json(url: str, headers: dict | None = None):
    """GET + JSON with retry on 5xx / connection errors. Non-transient -> GatherError."""
    req = urllib.request.Request(url, headers=headers or {})

    def _once():
        try:
            with urllib.request.urlopen(req, timeout=HTTP_TIMEOUT_S) as resp:
                return json.loads(resp.read().decode())
        except urllib.error.HTTPError as exc:
            if exc.code in (500, 502, 503, 504):
                raise _TransientHTTP(f"HTTP {exc.code} for {url}") from exc
            raise GatherError(f"HTTP {exc.code} for {url}") from exc
        except urllib.error.URLError as exc:
            raise _TransientHTTP(f"network error for {url}: {exc.reason}") from exc

    return _retry(_once, attempts=3, base_delay=2, transient=(_TransientHTTP,))


# ------------------------------------------------------------------ window
def week_window(anchor: dt.date) -> tuple[dt.date, dt.date]:
    """(week_start, week_end): the most recent Sunday at/before `anchor`, and
    the following Sunday — a pure function of the calendar date. Asia/Jerusalem
    throughout (the Mac's own local date; unlike a live data feed, MusicBrainz
    release dates aren't tied to one specific timezone, so there's no separate
    data-source zone to reconcile)."""
    days_since_sunday = (anchor.weekday() + 1) % 7  # Python: Mon=0..Sun=6 -> Sun=0
    week_end = anchor - dt.timedelta(days=days_since_sunday)
    week_start = week_end - dt.timedelta(days=7)
    return week_start, week_end


# ------------------------------------------------------------------ watch list
def normalize_variant(name: str) -> str:
    """One light fallback normalization (& vs and, leading 'The ', extra
    whitespace) — used only when the exact name doesn't confidently match;
    never used to guess between genuinely different artists."""
    v = re.sub(r"\s+", " ", name).strip()
    v = v.replace("&", "and")
    if v.lower().startswith("the "):
        v = v[4:]
    return v


def read_watch_list() -> list[str]:
    music = pd.read_excel(
        WATCHLIST_XLSX, sheet_name=WATCHLIST_MUSIC_SHEET, header=0,
        usecols=WATCHLIST_MUSIC_COL,
    ).iloc[:, 0].dropna().astype(str).str.strip()

    listen = pd.read_excel(
        WATCHLIST_XLSX, sheet_name=WATCHLIST_LISTEN_SHEET, header=0,
        usecols=WATCHLIST_LISTEN_COL,
    ).iloc[:, 0].dropna().astype(str)
    listen_artists = listen.str.split(" - ", n=1).str[0].str.strip()

    combined = sorted({a for a in set(music) | set(listen_artists) if a})
    return combined


# --------------------------------------------------------------- MusicBrainz
def _mb_get(path: str, params: dict) -> dict:
    url = f"{MB_BASE}/{path}?{urllib.parse.urlencode(params)}"
    headers = {"User-Agent": MB_USER_AGENT, "Accept": "application/json"}
    data = http_get_json(url, headers=headers)
    time.sleep(MB_RATE_DELAY_S)
    return data


def resolve_artist_mbid(name: str) -> str | None:
    candidates = [name]
    normalized = normalize_variant(name)
    if normalized != name:
        candidates.append(normalized)
    for candidate in candidates:
        data = _mb_get("artist/", {"query": f'artist:"{candidate}"', "fmt": "json", "limit": 3})
        hits = data.get("artists", [])
        if hits and hits[0].get("score", 0) >= MB_SEARCH_SCORE_THRESHOLD:
            return hits[0]["id"]
    return None


def releases_in_window(
    mbid: str, week_start: dt.date, week_end_excl: dt.date,
) -> tuple[list[dict], list[str]]:
    """(hits, precision_skipped_titles). hits: studio albums (no secondary
    types) with a full-day-precision first-release-date inside
    [week_start, week_end_excl). precision_skipped_titles: release-groups
    that matched the window's date-range query but only had year/month
    precision, so couldn't be confirmed in-window — rare, logged, not a
    blocker."""
    last_day = week_end_excl - dt.timedelta(days=1)
    query = (f"arid:{mbid} AND type:album AND "
             f"firstreleasedate:[{week_start.isoformat()} TO {last_day.isoformat()}]")
    data = _mb_get("release-group", {"query": query, "fmt": "json", "limit": 25})
    hits, imprecise = [], []
    for g in data.get("release-groups", []):
        if g.get("secondary-types"):
            continue
        d = g.get("first-release-date") or ""
        if len(d) == 10 and week_start.isoformat() <= d < week_end_excl.isoformat():
            hits.append(g)
        elif d:
            imprecise.append(g.get("title", "?"))
    return hits, imprecise


def studio_discography(mbid: str) -> list[dict]:
    """This artist's studio albums (no secondary types), sorted by
    first-release-date ascending. Paginates through every release-group
    MusicBrainz has for this artist under type=album (which also includes
    live/compilation/soundtrack entries sharing that primary type) so a
    prolific back-catalogue never causes a wrong or missing Number from a
    partial fetch — only called for the handful of artists with an actual
    hit this week, so the extra page(s) are cheap."""
    all_raw: list[dict] = []
    offset = 0
    while True:
        data = _mb_get(
            "release-group",
            {"artist": mbid, "type": "album", "fmt": "json",
             "limit": MB_MAX_RELEASE_GROUPS, "offset": offset},
        )
        batch = data.get("release-groups", [])
        all_raw.extend(batch)
        total = data.get("release-group-count", len(all_raw))
        offset += len(batch)
        if not batch or offset >= total:
            break
    return sorted(
        (g for g in all_raw if not g.get("secondary-types") and g.get("first-release-date")),
        key=lambda g: g["first-release-date"],
    )


def compute_number(all_groups: list[dict], target_id: str) -> str:
    for i, g in enumerate(all_groups, start=1):
        if g["id"] == target_id:
            return str(i)
    return ""


# --------------------------------------------------------------- artist cache
def _load_artist_cache() -> dict:
    try:
        return json.loads(ARTIST_CACHE_FILE.read_text())
    except Exception:  # noqa: BLE001 - missing / unreadable -> start fresh
        return {}


def _save_artist_cache(cache: dict) -> None:
    ARTIST_CACHE_FILE.parent.mkdir(parents=True, exist_ok=True)
    ARTIST_CACHE_FILE.write_text(json.dumps(cache, indent=2, ensure_ascii=False) + "\n")


# ------------------------------------------------------------------- gather
def gather(week_start: dt.date, week_end: dt.date) -> tuple[list[dict], list[str]]:
    """Return (rows, failed). rows: dicts with artist/album/number/date,
    sorted oldest->newest release date. failed: artist names whose
    MusicBrainz lookup genuinely errored (not just unmatched) — logged and
    skipped, not fatal unless every artist fails."""
    try:
        artists = read_watch_list()
    except Exception as exc:  # noqa: BLE001 - a broken/moved spreadsheet aborts the run
        raise GatherError(f"failed to read watch list from {WATCHLIST_XLSX.name}: {exc}") from exc
    log(f"watch list - {len(artists)} unique artists (Music col C + Listen col A)")

    cache = _load_artist_cache()
    rows: list[dict] = []
    failed: list[str] = []
    new_lookups = unmatched = 0

    for name in artists:
        entry = cache.get(name)
        if entry is None:
            new_lookups += 1
            try:
                mbid = resolve_artist_mbid(name)
            except GatherError as exc:
                log(f"[{name}] artist lookup failed, skipped: {exc}")
                failed.append(name)
                continue
            entry = {"mbid": mbid, "matched": mbid is not None}
            cache[name] = entry
        if not entry["matched"]:
            unmatched += 1
            continue

        mbid = entry["mbid"]
        try:
            hits, imprecise = releases_in_window(mbid, week_start, week_end)
        except GatherError as exc:
            log(f"[{name}] release check failed, skipped: {exc}")
            failed.append(name)
            continue
        if imprecise:
            log(f"[{name}] excluded (date precision too coarse to confirm "
                f"in-window): {', '.join(imprecise)}")
        if not hits:
            continue

        try:
            all_groups = studio_discography(mbid)
        except GatherError as exc:
            log(f"[{name}] discography fetch failed - Number left blank: {exc}")
            all_groups = []

        for g in hits:
            rows.append({
                "artist": name,
                "album": g.get("title", "?"),
                "number": compute_number(all_groups, g["id"]),
                "date": g["first-release-date"],
            })

    _save_artist_cache(cache)
    if artists and len(failed) == len(artists):
        raise GatherError("every artist lookup failed - MusicBrainz likely unreachable")

    log(f"resolved - {new_lookups} new lookups, {unmatched} unmatched, "
        f"{len(failed)} failed, {len(rows)} release(s) found this week")
    rows.sort(key=lambda r: r["date"])
    return rows, failed


# ------------------------------------------------------------------- assemble
def _cell(s: str) -> str:
    return s.replace("|", "\\|")


def render_body(rows: list[dict]) -> str:
    if not rows:
        return "No new studio album releases this week."
    lines = ["| Artist | Album | Number | Release Date |", "|---|---|---|---|"]
    for r in rows:
        lines.append(
            f"| {_cell(r['artist'])} | {_cell(r['album'])} | {r['number']} | {r['date']} |"
        )
    return "\n".join(lines)


def build_entry(week_end: dt.date, rows: list[dict]) -> str:
    key = f"{week_end.strftime('%a')}, {week_end.strftime('%d.%m.%Y')}"
    return f"## {key}\n\n{render_body(rows)}\n"


_HEADING_RE = r"^## \w+, \d{2}\.\d{2}\.\d{4}"


def _drop_existing_entry(entries_block: str, key: str) -> str:
    out: list[str] = []
    skipping = False
    for line in entries_block.splitlines():
        if re.match(_HEADING_RE, line):
            skipping = line.startswith(f"## {key}")
        if not skipping:
            out.append(line)
    return "\n".join(out).strip("\n")


def _week_already_logged(key: str) -> bool:
    """True if `key`'s heading already appears in the real output file — a
    scan this expensive (~1150 artists against MusicBrainz) shouldn't be
    silently redone by a launchd double-fire or an accidental re-run. Checks
    the real file regardless of --dry-run (cheap, and mirrors 04's guard not
    being sandboxed either); --force bypasses this."""
    if not OUTPUT_FILE.exists():
        return False
    return any(
        line.startswith(f"## {key}")
        for line in OUTPUT_FILE.read_text().splitlines()
    )


def upsert_entry(entry: str, key: str) -> str:
    content = OUTPUT_FILE.read_text() if OUTPUT_FILE.exists() else INTRO
    marker = "\n---\n"
    idx = content.find(marker)
    head = content[: idx + len(marker)] if idx != -1 else INTRO
    rest = content[idx + len(marker):].lstrip("\n") if idx != -1 else ""
    rest = _drop_existing_entry(rest, key)
    parts = [head.rstrip(), "", entry.rstrip()]
    if rest:
        parts += ["", rest.rstrip()]
    return "\n".join(parts).rstrip() + "\n"


# ---------------------------------------------------------------------- main
def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Generate this week's new-releases entry.")
    p.add_argument("--date", metavar="YYYY-MM-DD",
                   help="anchor the week to this date instead of today "
                        "(for testing / backfill)")
    p.add_argument("--dry-run", action="store_true",
                   help="write output/_preview.md only; touch no real files")
    p.add_argument("--force", action="store_true",
                   help="redo the scan even if this week is already logged "
                        "(normally skipped - this scan is expensive)")
    a = p.parse_args(argv)
    if a.date:
        try:
            a.date_obj = dt.date.fromisoformat(a.date)
        except ValueError:
            p.error(f"--date must be YYYY-MM-DD, got {a.date!r}")
    else:
        a.date_obj = None
    return a


def main(argv: list[str] | None = None) -> int:
    global _LOG_TO_FILE
    args = parse_args(argv)
    if args.dry_run:
        _LOG_TO_FILE = False

    anchor = args.date_obj or dt.date.today()
    week_start, week_end = week_window(anchor)
    key = f"{week_end.strftime('%a')}, {week_end.strftime('%d.%m.%Y')}"

    mode = "DRY RUN" if args.dry_run else "run"
    log(f"{mode} start - week {week_start.isoformat()} -> {week_end.isoformat()} "
        f"({RUN_TIMEZONE})")

    if not args.force and _week_already_logged(key):
        detail = f"already logged for {key} - skipped (use --force to redo)"
        log(detail)
        _record("skipped_duplicate", detail, entry=key)
        return 0

    try:
        rows, failed = gather(week_start, week_end)
    except GatherError as exc:
        log(f"ERROR gathering: {exc}")
        _record("error", str(exc), entry=key)
        return 1

    entry = build_entry(week_end, rows)
    new_body = upsert_entry(entry, key)

    if args.dry_run:
        PREVIEW_FILE.parent.mkdir(parents=True, exist_ok=True)
        PREVIEW_FILE.write_text(new_body)
        log(f"dry run - {OUTPUT_FILE.name} NOT touched; preview at "
            f"{PREVIEW_FILE.relative_to(PROJECTS_ROOT)} ({len(new_body)} bytes)")
        return 0

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(new_body)
    detail = f"wrote {OUTPUT_FILE.relative_to(PROJECTS_ROOT)} ({len(new_body)} bytes); {len(rows)} release(s)"
    if failed:
        detail += f"; PARTIAL - {len(failed)} artist lookups failed: {', '.join(failed)}"
    log(detail)
    _record("partial" if failed else "ok", detail, entry=key)
    return 0


if __name__ == "__main__":
    _started = dt.datetime.now().isoformat(timespec="seconds")
    _code, _ran = 1, False
    try:
        _code = main()
        _ran = True
    except Exception as exc:  # noqa: BLE001 - record, then re-raise the exit
        _record("error", f"uncaught: {exc!r}")
        traceback.print_exc()
        _ran = True
    finally:
        # skip on --help / bad args (SystemExit, _ran stays False) and on
        # --dry-run (_LOG_TO_FILE is False)
        if _ran and _LOG_TO_FILE:
            write_state(_code, _started)
    raise SystemExit(_code)
